services:
  postgres-identity:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_IDENTITY_NAME}
      - POSTGRES_USER=${DB_IDENTITY_USER}
      - POSTGRES_PASSWORD=${DB_IDENTITY_PASSWORD}
    volumes:
      - pgdata_identity:/var/lib/postgresql/data
    ports:
      - "${DB_IDENTITY_PORT:-5433}:5432"

  identity-service:
    build:
      context: .
      dockerfile: Dockerfile.identity-service
    env_file:
      - .env
    environment:
      - DB_IDENTITY_PORT=${DB_DOCKER_IDENTITY_PORT}
      - DB_IDENTITY_HOST=${DB_DOCKER_IDENTITY_HOST}
    ports:
      - "${PORT_IDENTITY:-4000}:4000"
    depends_on:
      - postgres-identity

  postgres-url:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_URL_SHORTENER_NAME}
      - POSTGRES_USER=${DB_URL_SHORTENER_USER}
      - POSTGRES_PASSWORD=${DB_URL_SHORTENER_PASSWORD}
    volumes:
      - pgdata_url:/var/lib/postgresql/data
    ports:
      - "${DB_URL_SHORTENER_PORT:-5434}:5432"

  short-url-service:
    build:
      context: .
      dockerfile: Dockerfile.short-url-service
    env_file:
      - .env
    environment:
      - DB_URL_SHORTENER_HOST=${DB_DOCKER_URL_SHORTENER_HOST}
      - DB_URL_SHORTENER_PORT=${DB_DOCKER_URL_SHORTENER_PORT}
    ports:
      - "${PORT_URL_SHORTENER:-4001}:4001"
    depends_on:
      - postgres-url
volumes:
  pgdata_url:
  pgdata_identity:
