# Building
FROM node:22.14.0-alpine AS builder

WORKDIR /app

COPY . .

# Enable corepack and install dependencies
RUN corepack enable && yarn install --immutable

WORKDIR /app/services/short-url-service

RUN yarn build

# Runtime
FROM node:22.14.0-alpine

WORKDIR /app

COPY --from=builder /app/services/short-url-service/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/services/short-url-service/package.json ./

EXPOSE 4001

CMD ["node", "dist/main"]
