name: CI
on: [push, pull_request]

env:
  node_version: "22.14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

<<<<<<< HEAD
      # First setup just to enable Corepack
      - name: Enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}

      - name: Initialize Yarn
        run: corepack enable

      # Second setup with caching
      - name: Setup Node.js with cache
=======
      - name: Setup Node and Yarn
>>>>>>> 21ce1bdbcf3b21b0663f717485e1218bb1accef1
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"

      - name: Install dependencies
        run: |
<<<<<<< HEAD
          yarn set version stable
          yarn install --immutable
=======
          corepack enable
          yarn set version stable
          yarn install
>>>>>>> 21ce1bdbcf3b21b0663f717485e1218bb1accef1

      - name: Run tests
        run: yarn test
