name: CI
on: [push, pull_request]

env:
  node_version: "22.14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Corepack first
      - name: Enable Corepack
        run: corepack enable

      # Then setup Node.js with cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"

      # Install Yarn Berry
      - name: Initialize Yarn
        run: yarn set version stable

      # Conditional lockfile handling
      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ] || [ -f ".yarn/install-state.gz" ]; then
            echo "Lockfile found - using immutable install"
            yarn install --immutable
          else
            echo "No lockfile found - creating with update-lockfile"
            yarn install --mode=update-lockfile
          fi

      - name: Run tests
        run: yarn test
