name: CI

on: [push, pull_request]

env:
  node_version: 22.14.0

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres-identity:
        image: postgres:14
        env:
          POSTGRES_DB: identity_db
          POSTGRES_USER: identity_user
          POSTGRES_PASSWORD: identity_password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready -U identity_user -d identity_db
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres-url:
        image: postgres:14
        env:
          POSTGRES_DB: url_shortener_db
          POSTGRES_USER: url_shortener_user
          POSTGRES_PASSWORD: url_shortener_password
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready -U url_shortener_user -d url_shortener_db
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js & Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint & format
        run: yarn lint && yarn format

      - name: Run unit tests
        run: yarn test:unit

      - name: Build and run services with docker-compose
        run: docker-compose -f ./docker-compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          npx wait-on http://localhost:4000   # Wait identity-service HTTP
          npx wait-on http://localhost:4001   # Wait short-url-service HTTP
          npx wait-on tcp:localhost:4002      # Wait identity-service TCP

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Shutdown docker-compose
        if: always()
        run: |
          echo "Current dir: $(pwd)"
          ls -la
          docker-compose -f ./docker-compose.yml down
