name: CI
on: [push, pull_request]

env:
  node_version: "22.14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Corepack setup must come first
      - name: Enable Corepack
        run: corepack enable

      # Node.js setup with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"

      # Yarn Berry initialization
      - name: Prepare Yarn
        run: yarn set version stable

      # Smart install with lockfile handling
      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            echo "Using existing lockfile"
            yarn install --immutable
          else
            echo "Generating new lockfile"
            yarn config set enableImmutableInstalls false
            yarn install
          fi

      - name: Run tests
        run: yarn test
