name: CI

on: [push, pull_request]

env:
  node_version: 22.14.0
  POSTGRES_IDENTITY_PORT: 5433
  POSTGRES_URL_SHORTENER_PORT: 5434

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres-identity:
        image: postgres:14
        env:
          POSTGRES_DB: identity_db
          POSTGRES_USER: identity_user
          POSTGRES_PASSWORD: identity_password
        ports:
          - ${{ vars.POSTGRES_IDENTITY_PORT }}:5432
        options: >-
          --health-cmd "pg_isready -U identity_user -d identity_db"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 15
          --health-start-period 10s

      postgres-url:
        image: postgres:14
        env:
          POSTGRES_DB: url_shortener_db
          POSTGRES_USER: url_shortener_user
          POSTGRES_PASSWORD: url_shortener_password
        ports:
          - ${{ vars.POSTGRES_URL_SHORTENER_PORT }}:5432
        options: >-
          --health-cmd "pg_isready -U url_shortener_user -d url_shortener_db"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 15
          --health-start-period 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment file
        run: cp .env.example .env

      - name: Load .env
        run: |
          set -a
          source .env
          set +a

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        timeout-minutes: 10
        env:
          DB_IDENTITY_HOST: localhost
          DB_IDENTITY_NAME: ${{ env.DB_IDENTITY_NAME }}
          DB_IDENTITY_PORT: ${{ env.POSTGRES_IDENTITY_PORT }}
          DB_IDENTITY_PASSWORD: ${{ env.DB_IDENTITY_PASSWORD }}
          DB_URL_SHORTENER_HOST: localhost
          DB_URL_SHORTENER_NAME: ${{ env.DB_URL_SHORTENER_NAME }}
          DB_URL_SHORTENER_PORT: ${{ env.POSTGRES_URL_SHORTENER_PORT }}
          DB_URL_SHORTENER_PASSWORD: ${{ env.DB_URL_SHORTENER_PASSWORD }}
        run: |
          yarn lint
          yarn format
          yarn test:unit
          yarn test:e2e

      - name: Cleanup
        if: always()
        run: docker compose down --remove-orphans
