name: CI
on: [push, pull_request]

env:
  node_version: 22.14.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js & Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: yarn
          cache-dependency-path: |
            .yarn/cache/**/*.zip
            yarn.lock
            .yarnrc.yml

      - name: Install & Test
        run: |
          yarn install --immutable
          yarn test
