name: CI
on: [push, pull_request]

env:
  node_version: "22.14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # First setup just to enable Corepack
      - name: Enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}

      - name: Initialize Yarn
        run: corepack enable

      # Second setup with caching
      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn set version stable
          yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
