name: CI
on: [push, pull_request]

env:
  node_version: "22.14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Corepack setup
      # 1. Corepack setup
      - name: Enable Corepack
        run: corepack enable

      # 2. Node.js setup with cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"

      # 3. Yarn Berry initialization (fixed config commands)
      # 3. Yarn Berry initialization (fixed config commands)
      - name: Prepare Yarn
        run: |
          yarn set version 4.9.1
          yarn config set enableImmutableInstalls --json false
          yarn config set checksumBehavior --json '"ignore"'

      # 4. Install dependencies
      # 4. Install dependencies
      - name: Install dependencies
        run: |
          if [ -f "yarn.lock" ]; then
            echo "Validating lockfile..."
            yarn install --immutable
            echo "Validating lockfile..."
            yarn install --immutable
          else
            echo "Generating lockfile..."
            echo "Generating lockfile..."
            yarn install
          fi

      - name: Run tests
        run: yarn test
