name: CI
on: [push, pull_request]

env:
  node_version: "22.14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"

      - name: Install dependencies
        run: |
          corepack enable
          yarn set version stable
          yarn install

      - name: Run tests
        run: yarn test
