name: CI

on: [push, pull_request]

env:
  node_version: 22.14.0

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres-identity:
        image: postgres:14
        env:
          POSTGRES_DB: identity_db
          POSTGRES_USER: identity_user
          POSTGRES_PASSWORD: identity_password
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U identity_user -d identity_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres-url:
        image: postgres:14
        env:
          POSTGRES_DB: url_shortener_db
          POSTGRES_USER: url_shortener_user
          POSTGRES_PASSWORD: url_shortener_password
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U url_shortener_user -d url_shortener_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node.js & Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint & format
        run: yarn lint && yarn format

      - name: Run unit tests
        run: yarn test:unit

      - name: Wait for PostgreSQL services
        timeout-minutes: 5
        run: |
          npx wait-on tcp:localhost:5433  # postgres-identity
          npx wait-on tcp:localhost:5434  # postgres-url

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Shutdown services
        if: always()
        run: docker compose down
